ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 새로운 사용자 계정 생성 (sys 계정으로 진행)
CREATE USER movie_project IDENTIFIED BY movie_project;

-- 사용자 계정 권한 부여 설정
GRANT RESOURCE, CONNECT TO movie_project;

-- 객체가 생성될 수 있는 공간 할당량 지정
ALTER USER movie_project DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

/***********************************************************************************/

CREATE TABLE "MEMBER" (
	"MEMBER_ID" VARCHAR2(50) PRIMARY KEY,
	"MEMBER_PW" VARCHAR2(100) NOT NULL,
	"MEMBER_NAME" VARCHAR2(50) NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 가입일';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 탈퇴여부';

INSERT INTO "MEMBER" VALUES('user01', 'pass01', '선동일', SYSDATE, 'N');
INSERT INTO "MEMBER" VALUES('user02', 'pass02', '송종기', SYSDATE, 'Y');
INSERT INTO "MEMBER" VALUES('user03', 'pass03', '유재식', SYSDATE, 'N');
INSERT INTO "MEMBER" VALUES('user04', 'pass04', '하이유', SYSDATE, 'N');

COMMIT;

SELECT * FROM "MEMBER";

/***********************************************************************************/

CREATE TABLE "COMM_CD" (
	"CODE_ID" VARCHAR2(20) NOT NULL,
	"CODE_NO" VARCHAR2(20) NOT NULL,
	"CODE_NAME" VARCHAR2(50) NOT NULL,
	CONSTRAINT CODE_PK PRIMARY KEY (CODE_NO, CODE_ID)
);

COMMENT ON COLUMN "COMM_CD"."CODE_ID" IS '코드 유형';
COMMENT ON COLUMN "COMM_CD"."CODE_NO" IS '코드';
COMMENT ON COLUMN "COMM_CD"."CODE_NAME" IS '코드명';

INSERT INTO "COMM_CD" VALUES('GENRE', '1', '판타지');
INSERT INTO "COMM_CD" VALUES('GENRE', '2', '드라마');
INSERT INTO "COMM_CD" VALUES('GENRE', '3', '액션');
INSERT INTO "COMM_CD" VALUES('GENRE', '4', '미스터리');
INSERT INTO "COMM_CD" VALUES('GENRE', '5', '공포');
INSERT INTO "COMM_CD" VALUES('GENRE', '6', '범죄');
INSERT INTO "COMM_CD" VALUES('GENRE', '7', '로맨스');

INSERT INTO "COMM_CD" VALUES('COUNTRY', 'US', '미국');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'KR', '대한민국');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'DE', '독일');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'RU', '러시아');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'GB', '영국');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'CN', '중국');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'TH', '태국');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'FR', '프랑스');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'HK', '홍콩');
INSERT INTO "COMM_CD" VALUES('COUNTRY', 'JPS', '일본');

COMMIT;

SELECT * FROM "COMM_CD";

/***********************************************************************************/

CREATE TABLE "MOVIE" ( 
	"MOVIE_NO" NUMBER PRIMARY KEY,
	"MOVIE_TITLE" VARCHAR2(100) NOT NULL,
	"GENRE" VARCHAR2(20),
	"PRODUCE" VARCHAR2(60),
	"COUNTRY" VARCHAR2(30),
	"RELEASE_DATE" DATE,
	"MOVIE_TIME" NUMBER DEFAULT 0,
	"INTRODUCE" VARCHAR2(1000),
	"MOVIE_REVIEW" VARCHAR2(1000),
	"RATING NUMBER" DEFAULT '0',
	"DIRECTOR" VARCHAR2(50),
	"MEMBER_ID" VARCHAR2(50) NOT NULL,
	"INS_DT" DATE DEFAULT SYSDATE,
	"MOVIE_DEL" CHAR(1) DEFAULT 'N' NOT NULL
);

CREATE SEQUENCE SEQ_MOVIE_NO NOCACHE;

INSERT INTO "MOVIE" VALUES(SEQ_MOVIE_NO.NEXTVAL, '윙카', '1', '헤이데이 필름스,빌리지 로드쇼 픽처스', 'US', '20240131', 
	112, '세상에서 가장 달콤한 여정 좋은 일은 모두 꿈에서부터 시작된다!', '',4, '폴킹', 'user01', SYSDATE, DEFAULT);

INSERT INTO "MOVIE" VALUES(SEQ_MOVIE_NO.NEXTVAL, '용감한 시민', '2', '㈜마인드마크', 'KR', '20231025', 
	112, '', '',3, '박진표', 'user02', SYSDATE, DEFAULT);

INSERT INTO "MOVIE" VALUES(SEQ_MOVIE_NO.NEXTVAL, '검은사제들', '2', 'CJ엔터테인먼트', 'KR', '20151105', 
	108, '', '',4, '장재현', 'user02', SYSDATE, DEFAULT);

INSERT INTO "MOVIE" VALUES(SEQ_MOVIE_NO.NEXTVAL, '파묘', '4', '쇼박스', 'KR', '20240222', 
	134, '', '',4, '장재현', 'user01', SYSDATE, DEFAULT);

INSERT INTO "MOVIE" VALUES(SEQ_MOVIE_NO.NEXTVAL, '사운드 오브 프리덤', '6', '(주)NEW', 'US', '20240221', 
	131, '세상에서 가장 달콤한 여정 좋은 일은 모두 꿈에서부터 시작된다!', '',4, '알레한드로 고메즈 몬테베르드', 'user01', SYSDATE, DEFAULT);

COMMIT;

SELECT * FROM "MOVIE";